### ISSUE TITLE
Problem with SuperChat display in some live room

### ISSUE THREAD

**Issue by IZUMI-Zu** [widcardw/D4nm4ku#4]
在一些直播间 SC 的展示似乎会被翻译为日文
目前在一些虚拟主播区的直播间会出现这种情况

![屏幕截图 2022-09-21 200021](https://user-images.githubusercontent.com/23271676/191499683-d6cc03fd-54fd-41e8-8c85-1ec732a6fc6e.png)

**Comment by widcardw** [comment]
原因：我选用的是 `SUPER_CHAT_MESSAGE_JPN`，详情见 _server.ts_ 的 [这一行](https://github.com/widcardw/D4nm4ku/blob/b168d1268317261b28a1040cebde114d670c4a57/src/composables/server.ts#L214)，因此该 SC 会被翻译为日文

**Comment by widcardw** [comment]
由于这一段我是按照 [3Shain/comen](https://github.com/3Shain/comen) 的代码来写的，如果需要显示中文的话，我构想两种方案

#### 方案一 将双语信息都保存到数据结构中，可以动态切换

- SuperChat 的数据结构中，`content` 字段的类型改为 `[string, string]`
- 给 `USCDanmaku.vue` 和 `USuperChatFloat.vue` 两个组件加上一个语言切换的按钮，当 `content` 字段的两个字符串都不为空时，点击按钮可以切换显示的语言

#### 方案二 通过全局配置，只显示一种语言

这一方案涉及到各种事件的传递，根据这一个配置项来更改 _server.ts_ 中的执行逻辑。如果注意到的话，在 `UWidget.vue` 中我注册了大量的事件监听，也可以看出来代码及其丑陋（x

**Comment by IZUMI-Zu** [comment]
ok 感谢回复
很棒的项目 期待大佬更新

**Comment by widcardw** [comment]
可以提供样例房间号吗，之后会尝试 dev 一下

**Comment by IZUMI-Zu** [comment]
8792912
22603245
我测试时这两个直播间会出现这个现象

**Comment by widcardw** [comment]
Fixed at [commit 84de6e](https://github.com/widcardw/D4nm4ku/commit/84de6eb6376d5fe292854423527d270b388b03c5)
